# Generated by Django 6.0.2 on 2026-02-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('numero_inventario', models.CharField(max_length=50, unique=True)),
                ('cantidad_total', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.laboratorio')),
            ],
        ),
    ]
