# Generated by Django 6.0.2 on 2026-05-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción detallada del daño reportado')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('En Reparacion', 'En Reparación'), ('Resuelta', 'Resuelta / Reparado'), ('Baja', 'Dado de baja (Pérdida total)')], default='Pendiente', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='equipment.equipo')),
            ],
        ),
    ]
