# Generated by Django 6.0.2 on 2026-02-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_prevista', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='En curso', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_danio', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipo')),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.prestamo')),
            ],
        ),
    ]
