# Generated by Django 6.0.2 on 2026-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
        ),
    ]
