# Generated by Django 6.0.2 on 2026-03-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
