# Generated by Django 6.0.2 on 2026-03-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_laboratorio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='facultad',
            field=models.CharField(default='FCC', max_length=50),
        ),
    ]
